Toggle just brackets around links
awth13/org-appear pull request #44
Opened 2022-03-22 04:05 UTC by jun0

Hey!  Nice work here!  I really like the idea behind this package.  I'm wondering if you can merge this small enhancement.

Showing everything inside a link can be disorienting, as URLs tend to be long, and showing them shifts all subsequent text by many characters.  The URL is also usually not interesting: it's just a technical detail of a link which is rarely inspected or updated.

This PR allows `org-appear-autolinks` to be set to `'just-brackets`, which instructs org-appear to show just a pair of brackets around a link under point, and no more.  This way, I get solid visual feedback on whether I'm typing inside or outside the link text, without seeing the link expand into a huge blob.  If I ever need to view/edit the URL, I can still use `org-insert-link`.

2022-04-01 11:50 UTC, awth13 commented
Hi and thank you for the PR, @jun0! I am sorry for not responding earlier.

I tried it out and it looks very good indeed. I do, however, have some comments about the code and formatting. Would you mind addressing these within the PR?

2022-04-02 08:23 UTC, jun0 commented
Sure, no problem.  What could I do to make it better?

2022-04-02 10:26 UTC, awth13 requested changes

2022-04-02 10:26 UTC, awth13 commented on org-appear.el
> +                  (< start visible-start visible-end end))
What is the purpose of this last check? For links with hidden elements, it will always evaluate to `t`, won't it?

2022-04-02 10:26 UTC, awth13 commented on org-appear.el
> +            ((and (eq elem-type 'link)
The rest of the code uses tabs and this part is using spaces for indenting, causing a visual mismatch in GitHub.

2022-04-02 10:26 UTC, awth13 commented on org-appear.el
> +  "Non-nil enables automatic toggling of links.  If set to
The first line of a docstring should be a complete sentence.

2022-04-02 10:26 UTC, awth13 commented on org-appear.el
>    :type 'boolean
If we allow `org-appear-autolinks` to have a `just-brackets` value, it is no longer a boolean. I think it should be a [choice of alternative types](https://www.gnu.org/software/emacs/manual/html_node/elisp/Composite-Types.html) now.

2022-04-03 02:06 UTC, jun0 commented on org-appear.el
> +                  (< start visible-start visible-end end))
Thanks for looking at this so closely.  I was just being defensive here because I wasn't 100% sure it was guaranteed.  I removed it.

2022-04-04 11:04 UTC, awth13 approved these changes

2022-04-04 11:15 UTC, awth13 commented
Thank you for implementing the changes!

While your approach of defining the type as `'(choice boolean (const just-brackets))` works, it is a little confusing for the end user in the customisation buffer. The user can toggle the boolean or choose the special `just-brackets` value. If I didn't know what's going on here, I would maybe assume that if I toggled it off, `org-appear` would ignore links regardless of `just-brackets`.

I suggest the following definition instead. It gives the user a clear choice of 3 options. Ideally, we would use another symbol instead of `t` for toggling full links but this would break existing user installs so I decided against it.

```
:type '(choice (const :tag "Ignore links" nil)
	       (const :tag "Toggle full link" t)
	       (const :tag "Toggle brackets" just-brackets))
```

Could you please implement this final change?

2022-04-05 00:21 UTC, jun0 commented
Good point!  I've implemented the change.

2022-04-05 11:46 UTC, merged

2022-04-05 11:47 UTC, awth13 commented
Thank you for your contribution! Merged.